# -*- coding: utf-8 -*-
"""Quantum-Lottery-Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVEKq-jBhLwTP7OsCJBTdNOT4hu3-B5l

Quantum Lottery Simulator - Gerador Quântico de Loterias
"""

# =============================================
# QUANTUM LOTTERY SIMULATOR
# Simulador Quântico de Loterias usando Cirq
# =============================================

print("🧪 QUANTUM LOTTERY SIMULATOR 🧪")
print("Gerando números com superposição quântica\n")

!pip install cirq
import cirq
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Markdown

display(Markdown("## Um projeto quântico feito por Santiago"))

def gerar_numero_quantico(minimo=1, maximo=60, qubits=6):
    """Gera um número usando qubits em superposição"""
    q = [cirq.LineQubit(i) for i in range(qubits)]
    circuito = cirq.Circuit()

    # Coloca todos os qubits em superposição
    for qubit in q:
        circuito.append(cirq.H(qubit))

    # Mede
    circuito.append(cirq.measure(*q, key='resultado'))

    simulador = cirq.Simulator()
    resultado = simulador.run(circuito, repetitions=1)

    bits = resultado.measurements['resultado'][0]
    numero = int(''.join(map(str, bits)), 2) % (maximo - minimo + 1) + minimo
    return numero

print("✅ Função quântica criada com sucesso!")

print("🎟️ GERANDO 10 JOGOS DA LOTOFÁCIL (15 números)\n")

jogos = []

for i in range(1, 11):
    numeros = set()
    while len(numeros) < 15:
        num = gerar_numero_quantico(1, 25, qubits=5)
        numeros.add(num)

    jogo = sorted(list(numeros))
    jogos.append(jogo)
    print(f"Jogo {i:2d}: {jogo}")

# Gráfico de frequência dos números
todos_numeros = [num for jogo in jogos for num in jogo]
plt.figure(figsize=(10, 6))
plt.hist(todos_numeros, bins=25, color='purple', alpha=0.7, edgecolor='black')
plt.title("Frequência dos Números Gerados Quanticamente")
plt.xlabel("Número")
plt.ylabel("Quantidade de vezes sorteado")
plt.grid(True)
plt.show()

display(Markdown("""
## 📖 Sobre o Projeto

Este é um **Simulador Quântico de Loteria** usando o framework **Cirq** do Google.

### O que foi feito:
- Uso de qubits em superposição para gerar aleatoriedade
- Geração de jogos da Lotofácil
- Visualização gráfica dos números
- Código organizado e comentado

**Tecnologias usadas:** Python, Cirq (Google Quantum), Matplotlib

Feito por Santiago como projeto de introdução à Computação Quântica.
"""))

print("🎟️ GERANDO 5 JOGOS DA MEGA-SENA (6 números de 1 a 60)\n")

for i in range(1, 6):
    numeros = set()
    while len(numeros) < 6:
        num = gerar_numero_quantico(1, 60, qubits=6)
        numeros.add(num)

    jogo = sorted(list(numeros))
    print(f"Mega-Sena {i}: {jogo}")

display(Markdown("""
## 🎯 Conclusão

Este projeto demonstra como podemos usar conceitos da **Computação Quântica** (superposição) mesmo usando um simulador.

### Aprendizados:
- Como criar circuitos quânticos
- Como medir qubits
- Como transformar resultados quânticos em números úteis

**Próximos passos possíveis:**
- Integrar com IA
- Criar uma interface web
- Fazer simulações mais complexas

---
**Obrigado por acompanhar!** 🧪
"""))

# =============================================
# QUANTUM LOTTERY SIMULATOR
# =============================================

!pip install cirq --quiet

import cirq
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Markdown

display(Markdown("# 🧪 Quantum Lottery Simulator"))
display(Markdown("### Usando Computação Quântica para gerar números de loteria"))

display(Markdown("""
## 📋 Sumário

1. Introdução à Computação Quântica
2. Gerador Quântico de Números
3. 10 Jogos da Lotofácil
4. 5 Jogos da Mega-Sena
5. Visualização Gráfica
6. Conclusão
"""))